### ISSUE TITLE
Subscription filter resetting after tab change

### ISSUE THREAD

**Issue by cshea15** [Azure/reliability-workbook#17]
When on a tab and filtering out the specific subscriptions, the filter only changes for the specific tab and not all of the tabs. So customers have to change the filter on every tab.

**Comment by tsubasaxZZZ** [comment]
Hi @cshea15, @infosatheesh2020,

I am working on resolving this issue.
Since this change is a little bit large, could you please review this workbook in your environment?

Workbook file: 
https://github.com/Azure/reliability-workbook/blob/32771868661d1c5ac44b1ce23cf33fe3f70a60e8/workbooks/Reliability%20v2.5.json

**Comment by tsubasaxZZZ** [comment]
Will fix v2.5 #25
